################################################################################
#                                                                              #
#     Create BrowserBox images with Travis                                     #
#                                                                              #
#                                                                              #
#      Copyright (C) 2020 Tom Stöveken                                         #
#                                                                              #
################################################################################

language: generic

# steps to do before the install
before_install:
  # 
  - sudo apt-get install -y qemu cloud-image-utils
  - wget https://cloud-images.ubuntu.com/minimal/daily/focal/current/focal-minimal-cloudimg-amd64.img
  - qemu-img create -b focal-minimal-cloudimg-amd64.img -f qcow2 larger.img 10G
  #- echo -e "#cloud-config\npassword: password123\nchpasswd: { expire: False }\nssh_pwauth: True\nhostname: nestedVM" > cloudconfig.txt
  #- cloud-localds cloudconfig.iso cloudconfig.txt
  #- qemu-system-x86_64 -accel tcg,thread=multi -smp 6 -hda larger.img -cdrom cloudconfig.iso -m 4096 -net nic -net user,hostfwd=tcp::22222-:22 -nographic

# perform the installation
install:
  # 
  - echo test

# perform actual job
script:
  - echo $PWD
  - echo $HOME
  - ls $PWD
  - cd $PWD

# notify result (passed or failed)
notifications:
  email:
    on_success: change
    on_failure: change
    
# upload compiled firmware as asset
#deploy:
#  provider: releases
#  api_key: $GITHUB_PERSONAL_ACCESS_TOKEN
#  file: "BrowserBox.ova"
#  skip_cleanup: true
#  on:
#    tags: true
